Passing scheduler host to start_tracker
dask/dask-xgboost pull request #77
Opened 2020-09-17 15:16 UTC by mmccarty

This was causing issues with our internal network. Please let me know if there is a more desirable fix.

2020-09-17 17:15 UTC, gforsyth commented
I'm not certain we want to do this / hard-code it -- if a user is using the `dask` helm chart then the `client.scheduler.address` will resolve to the reverse-proxy service instead of the scheduler pod

2020-09-18 14:07 UTC, mmccarty commented
Good catch! Is there any way we can test for this? I'll think of a another approach.

2020-09-25 14:39 UTC, mmccarty commented
@gforsyth CI was flaky but looks like it is passing now. What do you think?

2020-09-29 13:13 UTC, gforsyth requested changes
Hey @mmccarty -- this looks like a reasonable approach to me, one suggestion for slightly better error handling (although errors coming from `xgboost` are always going to be cryptic)

2020-09-29 13:13 UTC, gforsyth commented on dask_xgboost/core.py
> +            host = default_host
```suggestion
            if default_host is not None:
                host = default_host
            else:
                raise
```

2020-09-29 14:44 UTC, mmccarty commented
hey @TomAugspurger I'm getting a lot of random seg faults in CI. Sorry to bug you. Do you know what's going on?

2020-09-30 11:11 UTC, TomAugspurger commented
No idea. I've restarted the job in hopes that it goes away.

2020-09-30 12:55 UTC, TomAugspurger commented
All green now.

2020-09-30 12:55 UTC, merged

2020-09-30 13:42 UTC, mmccarty commented
Thanks!